### ISSUE TITLE
NLP sąvokos

### ISSUE THREAD

**Issue by LukasCed** [linas-p/ML-AI-2-LT#1]
Sveiki, ačiū už iniciatyvą. Norėčiau sužinoti, kaip galima versti šias frazes:

Token, tokenization (pvz., transformatorių kontekste. [nuoroda į pvz](https://albertauyeung.github.io/2020/06/19/bert-tokenization.html/) 
Slot, slot-filling (dialogo sistemų kontekste. [nuoroda į pvz](https://paperswithcode.com/task/slot-filling#:~:text=The%20goal%20of%20Slot%20Filling,to%20retrieve%20the%20appropriate%20information.)

**Comment by linas-p** [comment]
@LukasCed 

Problema yra nes jau turime informatikoje sąvoką Token - _žetonas_. Pažodinis vertimas, kuris nėra labai gerai skambantis:

Token (NLP) - žetonas, tai skaitinė reikšmė indeksas nusakantis fiksuotą simbolį, žodžio dalį
arba žodį. 

Kitas reikalas su sąvoka - tokenization. Kripo reikaluose turime '_žetonizacija_' -
procesas sukurti/išleisti žetonus į rinką. Natūralios kalbos apdorojime manau 
matyt tai būtų mažiausiai skausminga tai pat.

Tokenization is a way of separating a piece of text into smaller units called tokens.
Žetonizavimo procesas vienareikšmiškai priskiria duotam tekstui sąrašą žetonų reikšmių (indeksų).

Word tokenization - Žetonizavimo procesas žetonų reikšmėms priskiriant unikalius teksto žodžius. 
Subword  tokenization  - Žetonizavimo procesas žetonų reikšmėms priskiriant unikalias teksto dalis. 
Character-based tokenization - Žetonizavimo procesas žetonų reikšmėms priskiriant unikalius teksto simbolius. 

Tokenizer - Žetonizavimo modelis/transformacija.

Pretrained Bert tokenizer provided by the library HuggingFace.
Egzistuojantis žetonizavimo modelis Bert buvo atsisiųstas iš bibliotekos HuggingFace.

**Comment by linas-p** [comment]
@LukasCed 

Nepažodinis vertimo vienas iš siūlymų:
Slot Filling - _scenarijaus parinkimas_.

The goal of Slot Filling is to identify from a running dialog different slots, which correspond to different parameters of the user’s query. 

Scenarijaus parinkimo uždavinio tikslas iš pokalbių roboto užklausos identifikuoti,
kurį iš skirtingų scenarijų pasirinkti, čia scenarijai atitinka vartotojo užklausas 
su skirtingais pasirinkimais.

For instance, when a user queries for nearby restaurants, key slots for location and preferred food are required for a dialog system to retrieve the appropriate information. 

Pavyzdys: kai vartotojas užklausia artimiausios kavinės, pokalbių robotui reikia suformuoti
atitinkamas užklausas ir pagal raktažodžius identifikuoti vietos scenarijus ir 
pageidaujamo maisto pasirinkimo scenarijus.

Thus, the main challenge in the slot-filling task is to extract the target entity.

Pagrindinis iššūkis - scenarijaus parinkimo uždavinyje yra teisingai indentifikuoti 
subjekto klasę tekste.

**Comment by linas-p** [comment]
@LukasCed Jurgita Kapočiūtė-Dzikienė, pateikė savo taikomą vertimą:

Token - _teksto vienetas_, tai skaitinė reikšmė - indeksas nusakantis fiksuotą simbolį, 
žodžio dalį arba žodį.

Tokenization - _Teksto skaidymas į teksto vienetus_

Tokenization is a way of separating a piece of text into smaller units called tokens.

Teksto skaidymas į teksto vienetus vienareikšmiškai priskiria duotam tekstui sąrašą teksto vienetų (indeksų).

Word tokenization - Teksto skaidymas į teksto vienetus tai procesas teksto vienetams priskiriant unikalius teksto žodžius.
Subword tokenization - Teksto skaidymas į teksto vienetus procesas teksto vienetams priskiriant unikalias teksto dalis.
Character-based tokenization - Teksto skaidymas į teksto vienetus procesas teksto vienetams priskiriant unikalius teksto simbolius.

Tokenizer - Teksto skaidymo į teksto vienetus modelis/transformacija.

Pretrained Bert tokenizer provided by the library HuggingFace.
Egzistuojantis teksto skaidymo į teksto vienetus modelis Bert buvo atsisiųstas iš bibliotekos HuggingFace.

**Comment by linas-p** [comment]
@LukasCed 
Jurgitos siūlymas antrai sąvokai:

Slot Filling - esybių parinkimas (entity - esybė; named entity is a real-world object, such as a person, location, organization, product, etc., that can be denoted with a proper name. It can be abstract or have a physical existence).

The goal of Slot Filling is to identify from a running dialog different slots, which correspond to different parameters of the user’s query.

Esybių parinkimo uždavinio tikslas iš pokalbių roboto užklausos identifikuoti,
kurį iš skirtingų esybių pasirinkti, čia esybės atitinka vartotojo užklausas
su skirtingais pasirinkimais.

For instance, when a user queries for nearby restaurants, key slots for location and preferred food are required for a dialog system to retrieve the appropriate information.

Pavyzdys: kai vartotojas užklausia artimiausios kavinės, pokalbių robotui reikia suformuoti
atitinkamas užklausas ir pagal raktažodžius identifikuoti vietą kaip esybę ir
pageidaujamo maisto pasirinkimą kaip esybę.

Thus, the main challenge in the slot-filling task is to extract the target entity.

Pagrindinis iššūkis - esybių parinkimo uždavinyje yra teisingai indentifikuoti
esybės klasę tekste.

**Comment by VirgisM** [comment]
> @LukasCed Jurgita Kapočiūtė-Dzikienė, pateikė savo taikomą vertimą:
> 
> Token - _teksto vienetas_, tai skaitinė reikšmė - indeksas nusakantis fiksuotą simbolį, žodžio dalį arba žodį.
> 
> Tokenization - _Teksto skaidymas į teksto vienetus_
> 
> Tokenization is a way of separating a piece of text into smaller units called tokens.
> 
> Teksto skaidymas į teksto vienetus vienareikšmiškai priskiria duotam tekstui sąrašą teksto vienetų (indeksų).
> 
> Word tokenization - Teksto skaidymas į teksto vienetus tai procesas teksto vienetams priskiriant unikalius teksto žodžius. Subword tokenization - Teksto skaidymas į teksto vienetus procesas teksto vienetams priskiriant unikalias teksto dalis. Character-based tokenization - Teksto skaidymas į teksto vienetus procesas teksto vienetams priskiriant unikalius teksto simbolius.
> 
> Tokenizer - Teksto skaidymo į teksto vienetus modelis/transformacija.
> 
> Pretrained Bert tokenizer provided by the library HuggingFace. Egzistuojantis teksto skaidymo į teksto vienetus modelis Bert buvo atsisiųstas iš bibliotekos HuggingFace.

Manau teskto skaidymas į teksto vienetos yra aiškesnis terminas, negu žetonavimas, nors ir ilgesnis.

**Comment by linas-p** [comment]
Saulius Gražulis (@sauliusg) siūlymas -

Žodžių dalių skaidymui - kalbotyros žodis - [morfema](https://lt.wikipedia.org/wiki/Morfema) :

Subword tokenization - Teksto skaidymas į morfemas procesas leksemoms priskiriant unikalias teksto dalis. 
Character-based tokenization - Teksto skaidymas į simbolius procesas simboliams priskiriant unikalius teksto simbolius.

**Comment by linas-p** [comment]
> Saulius Gražulis (@sauliusg) siūlymas -
> 
> Žodžių dalių skaidymui - kalbotyros žodis - [morfema](https://lt.wikipedia.org/wiki/Morfema) :
> 
> Subword tokenization - Teksto skaidymas į morfemas procesas leksemoms priskiriant unikalias teksto dalis. Character-based tokenization - Teksto skaidymas į simbolius procesas simboliams priskiriant unikalius teksto simbolius.

Problema, jog skaidymas gal būti ir žodžių, bei simbolių lygyje. Todėl galima patikslinti, kad teksto vienetas priklausomai nuo metodo gali būti simbolis, morfema ar žodis.
