### ISSUE TITLE
Sąvokų siūlymai (nesubalansuotų duomenų aibės)

### ISSUE THREAD

**Issue by Dautartas** [linas-p/ML-AI-2-LT#16]
Nesubalansuotų duomenų aibės / Nesubalansuoti duomenys (angl. Imbalanced data)
Daugumos klasė (angl. Majority class)
Mažumos klasė (angl. Minority class)
Neigiama klasė (angl. Negative class)
Teigiama klasė (angl. Positive class)
Neigiami pavyzdžiai (angl. Negative instances)
Teigiami pavyzdžiai (angl. Positive instances)
Pavyzdžių generavimas (angl. Oversampling)
Pavyzdžių šalinimas (angl. Undersampling)
Įkainotas mokymasis (angl. Cost-sensitive learning)
Ansamblis (angl. Ensemble)
Požymių erdvė (angl. Feature space)

**Comment by linas-p** [comment]
@Dautartas  Dalis sąvokų vertimas, nelabai pažodinis, geresnė alternatyva:

Kaštams jautrus mokymasis (angl. Cost-sensitive learning)
Pavyzdžių perteklinis įtraukimas (angl. Oversampling)
Pavyzdžių retesnis įtraukimas (imties retinimas) (angl. Undersampling)
Dažniausia klasė (angl. Majority class)
Rečiausia klasė (angl. Minority class)
