### ISSUE TITLE
Neteisingai sulietuvinta Fréchet pavardė. (Fréchet inception distance)

### ISSUE THREAD

**Issue by Alotar** [linas-p/ML-AI-2-LT#2]
Fréchet buvo prancūzas, tai būtų "Frešė". Aš siūlyčiau apskritai palikti originalo kalba.

**Comment by linas-p** [comment]
@Alotar Patikslinau:
Frešė atstumas vaizdams.
_Inception_ modifikacija yra generalizacija vaizdams.
Yra analogiškos audio signalams, video ir pan. ir jis skiriasi tiesiog nuo Frešė atstumo skirstiniams.
