### ISSUE TITLE
Kaip išversti kelias sąvokas?

### ISSUE THREAD

**Issue by Deminalla** [linas-p/ML-AI-2-LT#22]
Sveiki. Norėčiau sužinot kaip būtų šie terminai išverčiami iš anglų į lietuvių
1. logit
2. Multinomial Naive Bayes (MNB)
3. Support Vector Machine (SVM)

**Comment by linas-p** [comment]
1. logit - logit (neverčiama, logit reikšmės)
2. Multinomial Naive Bayes (MNB) - Multinominis bajeso metodas
3. Support Vector Machine (SVM) - Atraminių vektorių metodas

**Comment by phonghm22** [comment]
Ok
