### ISSUE TITLE
Sąvokų pasiūlymai (text2image, tokenizer, scheduler it kt.)

### ISSUE THREAD

**Issue by modestasgrz** [linas-p/ML-AI-2-LT#5]
Naujos:

Text2image – grafinė kontekstualizacija (alternatyvos: TįV; Tekstas-Vaizdas; vaizdų generavimas iš tekstinės įvesties)
Denoising – triukšmo šalinimas
Zero-shot linear classifier – tiesinis klasifikatorius
Variance schedule – dispersijos grafikas
Cross-attention – kryžminis dėmesio sutelkimas
Feature extractor – požymių ekstraktorius
Learning rate scheduler – mokymo žingsnio planuotojas
Noise scheduler – triukšmo planuotojas

Siūlomi pakeitimai:

Tokenizer – "Teksto skaidymo į teksto vienetus modelis/transformacija" keisti į "Tokenizatorius", t.y., palikti tarptautinį žodį, esamasis vertimas atrodo per ilgas

**Comment by linas-p** [comment]
Labiau tiktų:

Text2image – Teksto transformavimas į vaizdą
Denoising – triukšmo šalinimas
Zero-shot linear classifier – tiesinis modelio adaptavimas klasifikavimui nepateikiant pavyzdžių
Variance schedule – dispersijos keitimo planuotojas
Cross-attention – kryžminis dėmesio sutelkimas
Feature extractor – informatyvių požymių ištraukimo metodas
Learning rate scheduler – mokymo žingsnio planuotojas
Noise scheduler – triukšmo keitimo planuotojas
